Connected onHover method [NEEDS FIXING]
Currently, an error is returned stating:
Error: The layer '[object Object]' does not exist in the map's style and cannot be queried for features.

TODO: Fix error so that the data is being pulled.